name:                Naproche-SAD
version:             0.1.0.0
github:              "Naproche/Naproche-SAD"
license:             GPL-3

extra-source-files:
- README.md

description:         <https://github.com/Naproche/Naproche-SAD>

dependencies:
- base >= 4.7 && < 5
- containers
- process
- time
- mtl
- transformers
- bytestring
- utf8-string
- network
- split

library:
  source-dirs:
    - src
    - Isabelle/src

executables:
  Naproche-SAD:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD

tests:
  Naproche-SAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
